# Generated by Django 4.0.5 on 2022-07-12 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='darmangar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(choices=[('طلاق', 'طلاق'), ('فرزند', 'فرزند'), ('خانواده', 'خانواده')], default=1, max_length=20)),
                ('fname', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
                ('lname', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('pic', models.ImageField(upload_to='darmanger-image')),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upl', models.FileField(upload_to='upload-file')),
            ],
        ),
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('slug', models.CharField(max_length=20, null=True, unique=True)),
                ('talk_about', models.TextField()),
                ('rel_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forms.darmangar')),
            ],
        ),
        migrations.CreateModel(
            name='darmanjo_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talk_about', models.TextField(blank=True, null=True)),
                ('information', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Forms.info')),
                ('rel_info', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Forms.darmangar')),
            ],
        ),
        migrations.CreateModel(
            name='Choice_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(choices=[('طلاق', 'طلاق'), ('فرزند', 'فرزند'), ('خانواده', 'خانواده')], default=1, max_length=20)),
                ('sessions', models.CharField(max_length=200)),
                ('information', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Forms.info')),
            ],
        ),
    ]
