# Generated by Django 4.0.5 on 2022-07-03 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0002_darmangar_remove_info_codemeli_info_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='darmanjo_form',
            name='information',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Forms.info'),
            preserve_default=False,
        ),
    ]
