# Generated by Django 4.0.5 on 2022-06-19 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0002_info_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='codemeli',
            new_name='mobile',
        ),
    ]
