# Generated by Django 4.0.5 on 2022-07-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0002_alter_darmanjo_form_rel_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='darmanjo_form',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
