# Generated by Django 4.0.5 on 2022-06-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0003_rename_codemeli_info_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='random_sms',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
