# Generated by Django 4.0.5 on 2022-06-19 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0004_info_random_sms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='random_sms',
            new_name='slug',
        ),
    ]
