# Generated by Django 4.0.5 on 2022-07-03 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0004_remove_darmanjo_form_rel_info_darmanjo_form_rel_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='darmanjo_form',
            name='rel_info',
        ),
        migrations.AddField(
            model_name='darmanjo_form',
            name='rel_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Forms.darmangar'),
            preserve_default=False,
        ),
    ]
