# Generated by Django 4.0.5 on 2022-08-21 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0004_darmangar_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='rel_info',
        ),
        migrations.RemoveField(
            model_name='info',
            name='talk_about',
        ),
    ]
