# Generated by Django 4.0.5 on 2022-08-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0005_remove_info_rel_info_remove_info_talk_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='mobile',
            field=models.IntegerField(max_length=100),
        ),
    ]
