# Generated by Django 4.0.5 on 2022-06-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0005_rename_random_sms_info_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='mobile',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='info',
            name='slug',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
