# Generated by Django 4.0.5 on 2022-06-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0006_alter_info_mobile_alter_info_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
