# Generated by Django 4.0.5 on 2022-07-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0007_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darmanjo_form',
            name='talk_about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
