# Generated by Django 4.0.5 on 2022-06-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0007_alter_info_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='mobile',
            field=models.CharField(max_length=100),
        ),
    ]
