# Generated by Django 4.0.5 on 2022-07-05 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0009_alter_darmanjo_form_rel_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darmanjo_form',
            name='information',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Forms.info'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='darmanjo_form',
            name='rel_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Forms.darmangar'),
        ),
        migrations.AlterField(
            model_name='darmanjo_form',
            name='talk_about',
            field=models.TextField(null=True),
        ),
    ]
