# Generated by Django 4.0.5 on 2022-07-05 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0012_darmangar_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='darmangar',
            old_name='choices',
            new_name='keyword',
        ),
    ]
