# Generated by Django 4.0.5 on 2022-07-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0013_rename_choices_darmangar_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(choices=[('طلاق', 'طلاق'), ('فرزند', 'فرزند'), ('خانواده', 'خانواده')], default=1, max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='keywords',
        ),
    ]
