# Generated by Django 4.0.5 on 2022-07-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0015_choice_model_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice_model',
            name='sessions',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
