# Generated by Django 4.0.5 on 2022-07-08 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0016_choice_model_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darmanjo_form',
            name='rel_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Forms.darmangar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='darmanjo_form',
            name='talk_about',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
