# Generated by Django 4.0.5 on 2022-07-08 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Forms', '0017_alter_darmanjo_form_rel_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darmanjo_form',
            name='rel_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Forms.darmangar'),
        ),
        migrations.AlterField(
            model_name='darmanjo_form',
            name='talk_about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
